---
title: "boat place feature"
description: |
  A short description of the post.
author:
  - name: Cam
    url: https://example.com/welcome
date: 04-29-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


S/V Real Life Revisited 
By Cameron Himes
March 22, 2021 

“So this is my interpretation that my Dad is like a super Adventure Guy and was obsessed with the idea of getting off the grid, and my mom liked that idea too. I think they read this book about getting off the grid, and like the guy in this book went and started a cheese farm. My Dad’s also like a total boat guy. Like in 4th grade, my fourth-grade year, he sailed across the Atlantic with like four random guys just for the sake of it. I think they were delivering something, but he just signed up for it so he could do it. We had a boat for a long time. They were like, OK, well this is something a lot of people do is like they like Cruise Bahamas on their sailboats like it’s big like it’s a big like Community of sailors that like to do this and my parents thought, “What better way to get off the grid than by boat and sail off in it?” Like that Zac Brown Band song Knee Deep. It’s like “bought a boat and sailed off in it… Don’t think anybody will miss me anyway.” That was the idea.” Madeline Taylor tells me over facetime how she found herself calling a 42-foot sailboat her home for nine months. 
According to her family’s blog, “S/V Real Life: A family of four on a one year sail,” Kevin Taylor writes, “Our trip. What exactly is it? On the surface, it is sailing down the east coast of Florida, on to the Florida Keys, the Bahamas and then we’ll see. Looking closer, it’s a family sabbatical. It’s taking hold of the fleeting time Kevin and I have with our children as children. For Kevin, from my perspective, it’s also answering the call that has been tapping his shoulder for as long as I have known him–sailing, voyaging. For me, it’s also embracing an inner challenge, self-discovery, and coveting time as a couple and a family.”
Madeline has mentioned how she spent her 7th grade year sailing the Bahamas to me a few times. But as our other friend pointed out, for a girl who says the phrase “fun fact” and then says something about herself, it’s odd that she rarely follows this experience as the fact. 
Madeline at almost 21 is now about 9 years removed from this off the grid experience. But she says the night before I spoke to her over facetime, she and her father plotted their next cruise. “And we were talking about how I would want to do it again someday and so kind of made a tentative plan like either next winter break or like the summer after I graduate, just like charter boat for three weeks, then kinda do like a miniature, same thing.” 

Madeline’s mom, dad and little brother set off from their hometown of Wheaton, IL in the beginning of August 2012. They would not see their house again until late May 2013. They drove to Fort Lauderdale, FL where their recently bought 42 foot Brewer was located. While sailing personal boats from the United States to the Bahamas wasn’t uncharted territory as there exists a community of past and current people continuing the voyage, it’s not easy. The Taylor family first lived in the Holiday Inn Express for about two months while the parents repaired the boat and the two kids, Zach, in 4th grade and Madeline, in 6th grade figured out their online school platforms. At the end of September, the family moved onto their boat, “The Real Life” and listened keenly to Chris Parker, the boating weather forecaster. “We had to line everything up with the weather. We couldn't leave too early or else it was still like hurricane season and we didn’t want to mess with that.” When Chris Parker gave the go aheads, the boat sailed to Miami and then at the end of November to Bimini in the Bahamas. 

“I'll never forget that night because it was so bad.” The family had enlisted a seasoned Irish sailor named Jerry who aided in their overnight journey across the Gulf Stream. Madeline has one major regret that night, “When you're like when you go down like so, there's like the Cockpit which is outside and was like where everyone was doing this stuff and then you go down like into the boat, which is where the actual living arrangements are. when you're like inside the boat was a little rocky. It is very easy to get seasick, so I was all like I'm not going down like I'm gonna stay there all night. And I’m so mad I didn't because if I went downstairs and took a melatonin and I just would fall asleep. Yeah, instead, I was adamant to sit on like this chair and I was getting splashed all night, which was rocky. And so I regretted that. And like the worst part of it all was like. I like 4 in the morning at like. We made a lot of progress right, but like since Miami is so bright you just look out on the horizon and like. You still see Miami.”


Madeline wished she had been in the small trapezoidal shaped room she shared with her brother. Zach’s side was decorated with “dinosaurs.” And Madeline’s was the “and to give you the mental picture of it, I was a 12 year old. I was obsessed with my J14 magazines. I wanted things to feel very normal, so I have a bright idea to put up on these Twilight posters. I wasn’t even that into Twilight but I had these posters and like One Direction posters, just like stuff that I cut out of the magazines like it wasn't like. Under Windows one was like on the ceiling like I forget who it was, but it might have been a One Direction poster on the ceiling. My brother's side was like dinosaurs. I also had a white board 'cause that was the first time I watched Mean Girls. I wrote all the funny Mean Girls quotes and I liked the picture of it like Oh my God so Tumblr. Oh my God. The pictures that I took from that you're like I was like peak 7th grade in 2012. So like. I'm literally like cringing about the pictures I posted on my Instagram and then like probably archived or maybe deleted? I don't know where they are.” Living with her brother, Madeline learned how to be content with herself and her thoughts often without Wifi or cellular service, something some people never learn. She can live on her own and appreciate people’s company but doesn’t need it because this experience fostered independence.
Because the siblings had to share a room on this traveling home, Madeline describes it as “actually it is the closest I've been with my brother. He and I were kinda like we know we knew we only had each other that year. Like any friends that we met, we were going to be friends for like 5 days until their boat sailed away.”

Maybe Madeline doesn’t pull this boathouse experience out everytime she needs a fun fact because it’s not really in that category. Living on a boat with her family molded her into the amazing person I know today. It made her so close to her family and showed her how to maintain special bonds. The boat brought the whole family together. One of their rituals was to watch Survivor the day after it was released. “The table didn't have a TV, but we would watch a lot of stuff on the computer like we would watch Survivor every week on the CBS website the day after.” Madeline was so passionate about Survivor and another favorite TV show, Dance Moms, she began a fan page for each. While the Survivor fandom continues as a hobby, Dance Moms inspired Madeline for something bigger. When she returned to Wheaton, IL, that May, she began her dance career, which continues to be a stabilizing force in her life and will remain a lifelong passion. 
Madeline didn’t just learn about her hobbies on this trip. She learned about people and met many different people. She developed her maturity by hanging out with older and wiser people. “Here is like an island called Farmer Cay which is in the Exuma which is like another island chain under Nassau. And farmers Cay is this point I guess in the middle where there's no phone service. There's like no Wi-Fi like no nothing like there were two restaurants on the entire island. One convenience store I think and there is 1 restaurant was right near the anchor where everybody was anchored and like there was Wi-Fi there and for the first few days we were there, I was glued to my iPad. Yeah, I met like our friends who I was talking about earlier like the three couples that we had met, yeah. Island and then one other couple we also met there and. We all just like to sit at the bar all day. And like I was this 13 year old at this point, and you know, I think I said 12. And we were all just sitting at the bar and like to sit at the table and like I would eat French fries and everything else. Adults would drink their Bahama drinks and there was a lot of camaraderie, so it just came to the point where I didn't want to be on my iPad anymore, 'cause I was having fun with my adult friends. I think that’s a part of why I'm as mature as I am today, because I spent a year only talking to adults, so I came back here after really 8th grade. It was like why is everybody so petty? like I realized how petty like the middle school drama was. OK. So I said about my adult friend. But yeah, it's like it's like practicing talking to adults.” Madeline is self aware but doesn’t look down on others. She was exposed to all different types of people and made friends with all of them. Madeline learned a lot of life lessons while living on a 42-foot long boat, but one the most valuable was her genuine kindness towards strangers. 


Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


