---
title: "trend feature"
description: |
  A short description of the post.
author:
  - name: Cam
    url: https://example.com/welcome
date: 04-29-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Fitness Trends Predict Many People Will Continue with At-Home Workout Routines, but Few GW Students Will 
By Cameron Himes
March 29, 2021 

CorePower Yoga Teacher in Tree Pose (courtesy of H Street location Facebook page) 

Before COVID-19, I would frequent the Georgetown Corepower Yoga Studio five to  six times a week. I loved this trendy hot yoga studio. It was a place I could get away from school and not have to think too hard.  This was more or less the norm for students and professionals in the area. As Jason Vanterpool, a DC based high-intensity interval exercise studio general manager, explains, “DC’s very type-A… we are all strong, independent people; we are very big thinkers. But when we leave work, we don’t want to think that much; we want to go and get our sweat in and work out — that’s why the classes are getting so big.” 
For me, the Corepower Yoga instructors created motivating environments with upbeat music and inspirational phrases as they led students through various classes, my favorite being yoga sculpt, which combines yoga poses with dumbbells and bodyweight movements in a 100 degree room. I even carved out 1.5-3 hours a week to clean the studio to cut down on my $149 per month student membership. But when I received an email from them earlier this year stating that I could go back on April 15th, I texted my friend, “idk, I’m not sure it’s going to be worth it. are you going to rejoin?” 
When COVID-19 hit, I went back to my childhood home in New Jersey to play out the last couple of weeks of my Junior year of college. I started taking my dogs for long walks and the occasional jog, and streaming Corepower yoga videos every day. When I moved back to DC, I even did them outside during the Summer to mimic the hot yoga environment. But as the weather got colder, I needed more variety than walks, occasional bike rides and yoga sculpt, so I started a free trial on the streaming website Obé Fitness which boasts 16 different at-home workouts with minimal equipment. I even coughed up the $199 annual fee because I found that this will stay with me as some of my other COVID habits. 
	According to journalist Elizabeth Segran,, “many experts say it’s important to have variety in your workout routine, and the pandemic has introduced people to options they’d never tried before.” My membership to Obé Fitness gives me access to live and on-demand pilates, yoga, barre, HIIT, cardio boxing, and strength workout classes ranging from 5 to 60 minutes. This variety is better for my body than doing the same  yoga and strength sequences every day.
I am not alone in realizing the affordability, convenience, and health benefits of at-home workouts compared to studio classes and university or private gyms. According to a survey of 3,500 Americans by ]Coefficient Capital, 76% of people have tried working out at home during the pandemic of those, 66% prefer it. This was especially pronounced among millennials, with  82% saying they had made the switch, and 81% saying they like it more. 
But I do seem to be in the minority within The George Washington University college students I asked about exercise habits. According to a Time article, “in a recent survey by consumer-spending experts the New Consumer and Coefficient Capital, 76% of respondents said they’ve tried working out at home during the pandemic, and 66% said they preferred it to the gym. In a July 2020 poll by financial-services firm TD Ameritrade, 59% of Americans said they don’t plan to renew their gym memberships post-pandemic, with 56% citing the appeal of more affordable ways to stay active.” Those who tried working out at home and didn’t enjoy it won’t continue for a couple of reasons, including safety, motivation, lack of amenities, and the specific experience of exercising in a workout studio. Multiple GW students have given testimony of why they will deviate from the more financially fiscal and convenient choice and will rejoin gyms and private fitness classes when they receive their COVID vaccine.
Safety 
Cece Myers, 20, a Junior at GW, used to run on her University gym’s indoor track “because I like running at night, but it’s safer inside.” When COVID-19 closed down in-person instruction and the University gym, she continued her 4-5 times a week workout schedule. Still, she switched to running faster sprints outside so she wouldn’t be out late at night and would be back inside earlier and watching the popular channel, Blogilates, for at-home pilates. She plans to go back to an indoor gym when she can. “I will go back to in-person gyms because I like working out kinda later in the evening, so I don’t need to worry about running alone at night.”
OrangeTheory Fitness West End/Foggy Bottom Location (source)
Motivation
	Before the pandemic hit, Sydney Barrena, 21, a Senior at GW, was so passionate about trying new workouts she held a position on the executive board of a student organization, CHAARG, that empowers girls to try different types of fitness classes. “Most of my workouts were group fitness classes, specifically hot yoga classes, spin classes, as well as other miscellaneous workout classes.” She swore by them so much so that when COVID cases were relatively low in her area, she returned to group fitness classes. “During the Summer, I began taking OrangeTheory workout classes, which are classes that focus on cardio, endurance, and strength training. Taking workout classes was a welcomed distraction and excuse to get out of the house when there were times I did not have a reason to leave my house” she explained. But as the weather cooled, she felt less confident in the COVID precautions and almost completely stopped going to OrangeTheory. For the most part however, she has not replaced her class with at-home workouts. “Honestly, I would say I work out from home much less than I worked out before the pandemic,” she explained. “I work out maybe two times a week from home. Before the pandemic, I mainly took group fitness classes as my primary form of working out, and I have found it hard to motivate myself to do workouts at home.” Will she return to group fitness classes though? “Yes, 100% yes, as soon as I am fully vaccinated, I will be going to workout classes. I cannot wait!” 	


Equinox Sports Club (source)

Cicely Williams, 21, also a Senior at GW, was a member of Equinox Sports Club until they discontinued their group fitness classes. She enjoyed “the interval training, along with a weekly cycling class.” She was even working with a personal trainer. Now she rarely works out because she misses the classes’ expertise and equipment at the private gym. When she didn’t have a scheduled class or workout time, she “lost a lot of motivation.” 
Amenities 
	The Time article also mentions how within the general public, “many people realize they don’t miss the eucalyptus-scented towels and designer toiletries they used to pay for at the gym.” But this is another draw of Equinox Sports Club for Cicely. Once she’s fully vaccinated and group fitness classes are easily accessible at the gym, she will go back partly because she misses the experience of the place and the motivation factors. “I miss the steam rooms and sauna, and those cool eucalyptus towels after I work out. The amenities make it all [the hard workout] worth it,” she says. 
Apartment Gyms & Outliers 
	Some students will continue to work out at “home” because their home is an apartment building with a fully equipped gym. Grace Robinson, 21, a Fall 2020 graduate of GW, may be one such  outlier because she started an avid fitness journey during the COVID pandemic. She didn’t experience as many studio classes pre-pandemic and never got into a routine of group classes. Grace very irregularly exercised before COVID. It was limited to free trials for fitness studios her roommate would drag her to. But when the pandemic hit, she started “a push towards a more healthy lifestyle on multiple fronts, diet, exercise, lifestyle choices, that occurred at the same time I graduated, which made me feel like I needed to adopt some adult habits.” This push was a trial and error. “At the beginning of COVID in 2020, I irregularly practiced yoga or short HITT workouts, no more than 30 minutes and no major sweat.” But when her fully equipped apartment gym opened she “ began to do longer and more varied workouts including HITT, weight routines, strength training, and elliptical at 45 min to an hour session lengths and 2-3 times a week.”
The Studio Boutique Experience 
	A Time article points out that “fancy gyms” and “studio boutiques” are unnecessary to a person’s health and “ most people [don’t] need them, research suggests… numerous studies have shown that virtually any amount of physical activity, done at any intensity, can help prevent chronic disease, boost longevity and improve mental health. (A stroll around the block or a 15-minute YouTube yoga class does make a difference.” 
George Washington University student’s deviation from the majority and readiness to return to studio group fitness classes and private gyms may result from the environment around them. As journalist Eliza Berkon points out, “boutique studios constitute much of the DC fitness space,” and going to workout studios in DC is now a luxury item experience. Most GW students see working out as more than a means to an end. They see it as an experience, one that is personalized, enjoyable, and sometimes social. This perspective is why many will return to boutique fitness studios and private gyms once everyone is vaccinated. 
Conclusion 
Part of the reason I looked to my friend for her option about returning to Corepower Yoga when it announced it would open up is because part of the studio fitness classes that appealed to me was the social aspect. I would go with friends and the anticipation, the walk there and back, the class itself, and sometimes an after class snack or drink was a bigger part of what I missed than I first realized. I found I was motivated enough to curate a similar workout environment at home with different types of workouts and without the social aspect the studio boutique itself wasn’t enough. I expected many of my other somewhat financially independent friends to have a similar perspective to me. But I guess the DC workout culture is too deeply ingrained in them. 


Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


